-- max_allowed_packet=4G (debe ser reemplazado pues viene con 1M por defecto) (se realiza en el my.ini de xamp (config de mysql))

CREATE DATABASE dwh_actividad1;
COMMIT;

USE dwh_actividad1;
COMMIT;

-- CREATE TABLE ESTUDIANTE
CREATE TABLE ESTUDIANTE (
    ID_CONSECUTIVO VARCHAR(255) PRIMARY KEY,
    FECHA_NACIMIENTO DATE,
    TIENE_ETNIA VARCHAR(2),
    ETNIA VARCHAR(255),
    DEDICACION_LECTURADIARIA VARCHAR(255),
    COLEGIO_COD_DANE_ESTABLECIMIENTO VARCHAR(255),
    GENERO VARCHAR(2),
    NACIONALIDAD VARCHAR(255),
    TIENE_NUMLIBROS VARCHAR(255),
    DEDICACION_INTERNET VARCHAR(255),
    HORAS_SEMANATRABAJA VARCHAR(255),
    GENERACION_E VARCHAR(255),
	EDUCACION_PADRE VARCHAR(255),
	EDUCACION_MADRE VARCHAR(255),
	TRABAJO_PADRE VARCHAR(255),
	TRABAJO_MADRE VARCHAR(255)
);
COMMIT;

-- CREATE TABLE PUNTAJE
CREATE TABLE PUNTAJE (
    ID_CONSECUTIVO VARCHAR(255) PRIMARY KEY,
    PUNT_GLOBAL FLOAT,
    PUNT_LECTURA_CRITICA FLOAT,
    PUNT_MATEMATICAS FLOAT,
    PUNT_CIENCIAS_NATURALES FLOAT,
    PUNT_SOCIALES_CIUDADANAS FLOAT,
    PUNT_INGLES FLOAT,
    DESEMP_INGLES VARCHAR(255)
);
COMMIT;

-- CREATE TABLE RESIDENCIA_ESTUDIANTE
CREATE TABLE RESIDENCIA_ESTUDIANTE (
    ID_CONSECUTIVO VARCHAR(255) PRIMARY KEY,
    COD_RESIDE_DEPTO VARCHAR(255),
    DEPTO_RESIDE VARCHAR(255),
    COD_MUNICIPIO_RESIDE VARCHAR(255),
    MUNICIPIO_RESIDE VARCHAR(255),
    PAIS_RESIDENCIA VARCHAR(255),
    ESTRATO_VIVIENDA VARCHAR(2),
    PERSONAS_HOGAR VARCHAR(255),
    CUARTOS_HOGAR VARCHAR(255)
);
COMMIT;

-- CREATE TABLE TECNOLOGIA_HOGAR
CREATE TABLE TECNOLOGIA_HOGAR (
    ID_CONSECUTIVO VARCHAR(255) PRIMARY KEY,
    TIENE_SERVICIOINTERNET VARCHAR(3),
    TIENE_COMPUTADOR VARCHAR(3),
    TIENE_CONSOLAVIDEOJUEGOS VARCHAR(3)
);
COMMIT;

-- CREATE TABLE COLEGIO
CREATE TABLE COLEGIO (
    COLEGIO_COD_DANE_ESTABLECIMIENTO VARCHAR(255) PRIMARY KEY,
    COLEGIO_NOMBRE_ESTABLECIMIENTO VARCHAR(255),
    COLEGIO_BILINGUE VARCHAR(255),
    COLEGIO_NATURALEZA VARCHAR(255),
    COLEGIO_CARACTER VARCHAR(255),
    COLEGIO_COD_DEPARTAMENTO_UBICACION VARCHAR(255),
    COLEGIO_DEPARTAMENTO_UBICACION VARCHAR(255),
    COLEGIO_COD_MUNICIPIO_UBICACION VARCHAR(255),
    COLEGIO_MUNICIPIO_UBICACION VARCHAR(255),
    COLEGIO_AREA_UBICACION VARCHAR(255),
    COLEGIO_JORNADA VARCHAR(255)
);
COMMIT;

-- Create user to conection user: "admin" pass: "root"
CREATE USER 'admin'@'localhost' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;